openapi: 3.0.0
info:
  title: Authentication API
  description: API documentation for user authentication and authorization
  version: 1.0.0

paths:
  /api/auth/register:
    post:
      summary: Register a new user
      tags: [Authentication]
      requestBody:
        description: User registration data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                email:
                  type: string
      responses:
        201:
          description: User created successfully
        400:
          description: Invalid input data
        500:
          description: Internal server error

  /api/auth/login:
    post:
      summary: Login a user
      tags: [Authentication]
      requestBody:
        description: User login data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: User logged in successfully
        401:
          description: Invalid credentials
        500:
          description: Internal server error