openapi: 3.0.0
info:
  title: Balance API
  description: API documentation for user balance management
  version: 1.0.0

paths:
  /api/balance/me:
    get:
      summary: Get current user's balance
      tags: [Balance]
      security:
        - bearerAuth: []
      responses:
        200:
          description: Current user's balance
        500:
          description: Internal server error

  /api/balance/{usuario_id}:
    get:
      summary: Get user's balance by ID (admin only)
      tags: [Balance]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: usuario_id
          schema:
            type: string
          required: true
          description: ID of the user
      responses:
        200:
          description: User's balance
        404:
          description: Balance not found
        500:
          description: Internal server error

    put:
      summary: Update user's balance (admin only)
      tags: [Balance]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: usuario_id
          schema:
            type: string
          required: true
          description: ID of the user
      requestBody:
        description: Balance data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
      responses:
        200:
          description: Balance updated successfully
        400:
          description: Invalid input data
        404:
          description: Balance not found
        500:
          description: Internal server error

    delete:
      summary: Delete user's balance (admin only)
      tags: [Balance]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: usuario_id
          schema:
            type: string
          required: true
          description: ID of the user
      responses:
        200:
          description: Balance deleted successfully
        404:
          description: Balance not found
        500:
          description: Internal server error

  /api/balance:
    post:
      summary: Create initial balance for a user (admin only)
      tags: [Balance]
      security:
        - bearerAuth: []
      requestBody:
        description: Balance data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                initialBalance:
                  type: number
      responses:
        201:
          description: Initial balance created successfully
        400:
          description: Invalid input data
        500:
          description: Internal server error