openapi: 3.0.0
info:
  title: Language API
  description: API documentation for language management
  version: 1.0.0

paths:
  /api/lang:
    get:
      summary: Change the language
      tags: [Language]
      parameters:
        - in: query
          name: lang
          schema:
            type: string
          required: true
          description: Language code
      responses:
        200:
          description: Language changed successfully
        400:
          description: Language parameter is required
        500:
          description: Internal server error