openapi: 3.0.0
info:
  title: Order API
  description: API documentation for order management
  version: 1.0.0

paths:
  /api/orders:
    post:
      summary: Create a new order
      tags: [Orders]
      security:
        - bearerAuth: []
      requestBody:
        description: Order data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                total:
                  type: number
                shipping_address:
                  type: string
                status:
                  type: string
                shipping_status:
                  type: string
      responses:
        201:
          description: Order created successfully
        400:
          description: Invalid input data
        500:
          description: Internal server error

    get:
      summary: Get all orders (admin only)
      tags: [Orders]
      security:
        - bearerAuth: []
      responses:
        200:
          description: List of all orders
        500:
          description: Internal server error

  /api/orders/me:
    get:
      summary: Get current user's orders
      tags: [Orders]
      security:
        - bearerAuth: []
      responses:
        200:
          description: List of current user's orders
        500:
          description: Internal server error

  /api/orders/cancel/{id}:
    post:
      summary: Request order cancellation
      tags: [Orders]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the order
      requestBody:
        description: Cancellation reason
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                reason:
                  type: string
      responses:
        200:
          description: Cancellation request submitted
        500:
          description: Internal server error

  /api/orders/{id}:
    get:
      summary: Get an order by ID (admin only)
      tags: [Orders]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the order
      responses:
        200:
          description: Order details
        404:
          description: Order not found
        500:
          description: Internal server error

    put:
      summary: Update an order (admin only)
      tags: [Orders]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the order
      requestBody:
        description: Order data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                total:
                  type: number
                shipping_address:
                  type: string
                status:
                  type: string
                shipping_status:
                  type: string
      responses:
        200:
          description: Order updated successfully
        400:
          description: Invalid input data
        404:
          description: Order not found
        500:
          description: Internal server error

    delete:
      summary: Delete an order (admin only)
      tags: [Orders]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the order
      responses:
        200:
          description: Order deleted successfully
        404:
          description: Order not found
        500:
          description: Internal server error