openapi: 3.0.0
info:
  title: Product API
  description: API documentation for product management
  version: 1.0.0

paths:
  /api/products:
    get:
      summary: Get all products
      tags: [Products]
      responses:
        200:
          description: List of all products
        500:
          description: Internal server error

    post:
      summary: Create a new product (admin only)
      tags: [Products]
      security:
        - bearerAuth: []
      requestBody:
        description: Product data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                price:
                  type: number
                categoryId:
                  type: string
      responses:
        201:
          description: Product created successfully
        400:
          description: Invalid input data
        500:
          description: Internal server error

  /api/products/{id}:
    get:
      summary: Get a product by ID
      tags: [Products]
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the product
      responses:
        200:
          description: Product details
        404:
          description: Product not found
        500:
          description: Internal server error

    put:
      summary: Update a product (admin only)
      tags: [Products]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the product
      requestBody:
        description: Product data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                price:
                  type: number
                categoryId:
                  type: string
      responses:
        200:
          description: Product updated successfully
        400:
          description: Invalid input data
        404:
          description: Product not found
        500:
          description: Internal server error

    delete:
      summary: Delete a product (admin only)
      tags: [Products]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the product
      responses:
        200:
          description: Product deleted successfully
        404:
          description: Product not found
        500:
          description: Internal server error

  /api/products/search:
    get:
      summary: Search for products
      tags: [Products]
      parameters:
        - in: query
          name: query
          schema:
            type: string
          required: true
          description: Search query
      responses:
        200:
          description: List of products matching the search query
        500:
          description: Internal server error