openapi: 3.0.0
info:
  title: User API
  description: API documentation for user management
  version: 1.0.0

paths:
  /api/users/me:
    get:
      summary: Get current user's information
      tags: [Users]
      security:
        - bearerAuth: []
      responses:
        200:
          description: Current user's information
        500:
          description: Internal server error

  /api/users:
    post:
      summary: Create a new user (admin only)
      tags: [Users]
      security:
        - bearerAuth: []
      requestBody:
        description: User data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                email:
                  type: string
      responses:
        201:
          description: User created successfully
        400:
          description: Invalid input data
        500:
          description: Internal server error

    get:
      summary: Get all users (admin only)
      tags: [Users]
      security:
        - bearerAuth: []
      responses:
        200:
          description: List of all users
        500:
          description: Internal server error

  /api/users/{id}:
    get:
      summary: Get a user by ID (admin only)
      tags: [Users]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the user
      responses:
        200:
          description: User details
        404:
          description: User not found
        500:
          description: Internal server error

    put:
      summary: Update a user (admin only)
      tags: [Users]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the user
      requestBody:
        description: User data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                email:
                  type: string
      responses:
        200:
          description: User updated successfully
        400:
          description: Invalid input data
        404:
          description: User not found
        500:
          description: Internal server error

    delete:
      summary: Delete a user (admin only)
      tags: [Users]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the user
      responses:
        200:
          description: User deleted successfully
        404:
          description: User not found
        500:
          description: Internal server error